from News.models import *
user1 = User.objects.create(username='Alex', first_name='Alexey')
user2 = User.objects.create(username='Tema', first_name='Artem')
Author.objects.create(user=user1)
Author.objects.create(user=user2)
Category.objects.create(category='School')
Category.objects.create(category='IT')
Category.objects.create(category='environment')
Category.objects.create(category='politics')
Post.objects.create(authors=Author.objects.get(user=User.objects.get(username='Alex')), type='AR', name='Iteresting story', text_post='It is realy interesting story')
Post.objects.create(authors=Author.objects.get(user=User.objects.get(username='Tema')), type='AR', name='Artkfdkkodk', text_post='ewewdww')
Post.objects.create(authors=Author.objects.get(user=User.objects.get(username='Alex')), type='NW', name='Good news', text_post='realy good news')
p1 = Post.objects.get(pk=1)
p2 = Post.objects.get(pk=2)
p3 = Post.objects.get(pk=3)
c1 = Category.objects.get(category='IT')
c2 = Category.objects.get(category='environment')
c3 = Category.objects.get(category='School')
c4 = Category.objects.get(category='politics')
p1.categories.add(c1)
p2.categories.add(c2, c3)
p3.categories.add(c4)
Comment.objects.create(users=User.objects.get(username='Alex'), posts=Post.objects.get(pk=1), text_com='goood')
Comment.objects.create(users=User.objects.get(username='Tema'), posts=Post.objects.get(pk=2), text_com='baaad')
Comment.objects.create(users=User.objects.get(username='Tema'), posts=Post.objects.get(pk=3), text_com='Oh nooo')
Comment.objects.create(users=User.objects.get(username='Tema'), posts=Post.objects.get(pk=1), text_com='So wanderfule')
>>> Post.objects.get(pk=1).like()
>>> Post.objects.get(pk=1).like()
>>> Post.objects.get(pk=1).like()
>>> Post.objects.get(pk=1).like()
>>> Post.objects.get(pk=1).like()
>>> Post.objects.get(pk=1).like()
>>> Post.objects.get(pk=1).like()
>>> Post.objects.get(pk=1).dislike()
Post.objects.get(pk=2).dislike()
>>> Post.objects.get(pk=2).dislike()
>>> Post.objects.get(pk=2).dislike()
Post.objects.get(pk=3).dislike()
>>> Post.objects.get(pk=3).dislike()
>>> Post.objects.get(pk=3).like()
>>> Post.objects.get(pk=3).like()
>>> Post.objects.get(pk=3).like()
Comment.objects.get(pk=1).like()
>>> Comment.objects.get(pk=2).dislike()
Author.objects.get(user=User.objects.get(username='Alex')).update_rating()
>>> Author.objects.get(user=User.objects.get(username='Tema')).update_rating()
best = Author.objects.all().order_by('-rating_auth').values('user','rating_auth')[0]
print(best)
best_u=User.objects.get(id=1)
print(best_u)
best_post=Post.objects.all().order_by('-rating_post').values('time_post', 'authors', 'rating_post', 'name')[
0]
>>> print(best_post) 
