# Generated by Django 4.1.5 on 2023-01-31 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='text_com',
            field=models.TextField(default=232),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='text_post',
            field=models.TextField(default=3323),
            preserve_default=False,
        ),
    ]
